set(THREADS_PREFER_PTHREAD_FLAG TRUE)
find_package(Threads REQUIRED)
find_package(XRT PATHS ${CMAKE_CURRENT_LIST_DIR})
find_package(SDx PATHS ${CMAKE_CURRENT_LIST_DIR})

include("${CMAKE_CURRENT_LIST_DIR}/FRTTargets.cmake")
