name: CI

on:
  - push

jobs:
  CI:
    runs-on:
      - self-hosted
      - Linux
      - xilinx-tools

    strategy:
      matrix:
        xocl-version:
          - 2019.2
          - 2020.2
          - 2021.1
          - 2021.2

    env:
      # Cannot source Xilinx scripts because they mess up many system libraries.
      XILINX_VITIS: /opt/tools/xilinx/Vitis/${{ matrix.xocl-version }}

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            libgflags-dev \
            libgoogle-glog-dev \
            libtinyxml-dev \
            opencl-headers \
            python3-pip \
            xilinx-u250-xdma-dev \
            xilinx-u280-xdma-dev \

          python3 -m pip install --user \
            git+https://github.com/Licheng-Guo/tapa-fast-cosim.git@02ecd87c4d24d6513d8c0d15af8046d5ee05a2ae
      - name: Configure myself
        run: cmake -S. -Bbuild
      - name: Build myself
        run: cmake --build build --target all
      - name: Test myself
        working-directory: build
        run: |
          # Some Vitis versions have a bug where xclbinutil is not found without
          # manually sourcing the XRT setup script.
          source "${XILINX_XRT}"/setup.sh
          # Vivado doesn't like running concurrently for the first time.
          (
            source "${XILINX_VITIS}"/settings64.sh
            vivado -mode batch -nojournal -nolog
          )
          ctest --verbose --parallel $(nproc)
      - name: Run TAPA fast cosim
        if: ${{ matrix.xocl-version == '2020.2' }}
        run: cmake --build build --target xdma-xosim
