name: CI

on:
  - push

jobs:
  CI:
    runs-on:
      - self-hosted
      - Linux
      - xilinx-tools

    strategy:
      matrix:
        xocl-platform:
          - xilinx_u250_gen3x16_xdma_4_1_202210_1
        xocl-version:
          - 2023.2

    env:
      # Cannot source Xilinx scripts because they mess up many system libraries.
      XILINX_HLS: /opt/tools/xilinx/Vitis_HLS/${{ matrix.xocl-version }}
      XILINX_VITIS: /opt/tools/xilinx/Vitis/${{ matrix.xocl-version }}
      XILINX_VIVADO: /opt/tools/xilinx/Vivado/${{ matrix.xocl-version }}

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            libgflags-dev \
            libgoogle-glog-dev \
            libgtest-dev \
            libtinyxml-dev \
            opencl-headers \
            python3-pip \

          python3 -m pip install --user \
            git+https://github.com/UCLA-VAST/tapa-fast-cosim.git@93646a999b786e94626982700dfaf708fe3deec0
      - name: Configure myself
        run: cmake -S. -Bbuild -DXRT_PLATFORM=${{ matrix.xocl-platform }}
      - name: Build myself
        run: cmake --build build --target all
      - name: Test myself
        working-directory: build
        run: |
          # Some Vitis versions have a bug where xclbinutil is not found without
          # manually sourcing the XRT setup script.
          source "${XILINX_XRT}"/setup.sh
          source "${XILINX_VITIS}"/settings64.sh
          /usr/bin/ctest --verbose --stop-on-failure
