name: install

on: page_build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4
      - name: Install from script
        run: ./install.sh
