name: package

on:
  push:
    tags:
      - "*"
    branches-ignore:
      - "**/docs?"
  pull_request:
    branches-ignore:
      - "**/docs?"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - name: Checkout myself
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          # https://bugs.launchpad.net/ubuntu/+source/google-glog/+bug/1991919
          sudo apt-get install -y libunwind-15-dev || true
          sudo apt-get install -y \
            libgflags-dev \
            libgoogle-glog-dev \
            libgtest-dev \
            libtinyxml-dev \
            opencl-headers \

          ./.github/scripts/install-xrt.sh
      - name: Configure myself
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build myself
        run: cmake --build build --target all
      - name: Test myself
        run: ctest --exclude-regex '.*-co?sim'
        working-directory: build
      - name: Package myself
        run: cmake --build build --target package
      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: frt-${{ matrix.os }}
          path: build/*.deb

  release:
    if: github.event_name == 'push' && github.repository == 'Blaok/fpga-runtime' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    concurrency: release
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    needs:
      - build
    steps:
      - name: Checkout myself
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: frt-${{ matrix.os }}
          path: build
      - name: Cache APT database
        uses: actions/cache@v3
        with:
          path: apt-db-cache
          key: ${{ runner.os }}-apt-db-cache
      - name: Update APT repository
        run: ./.github/scripts/upload-apt-repo.sh
        env:
          BUILD_DIR: build
          CACHE_DIR: apt-db-cache
          LABEL: FPGA Runtime Repository
          GPG_KEY: ${{ secrets.GPG_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
